sudo: false
language: ruby
rvm:
- 2.5.1
- 2.4.3
- 2.3.7
before_install: gem install bundler -v 1.16.1
notifications:
  slack:
    secure: no8/ZtMrQm8EyglLJW9toPdKGwa7g1+AcWwlnzH7HCAp9dSafETt5HOIxzIecotVFV+VCoHi1lrHnJoyJ8svOfro9Jh1i1+oZzW+eHH/Df4AVyPOPLlJINoLi/SP+d7NTgS4+oVYB/y7uPC9y7QkdaTxGC540OaXmbVbw7M/GSMv7n6qVOmdMnH/JeH9qjHkJ3FUmnnWY2AVlUrcpERIOcdB4zN65b+7zMUUGqAXnbpTOrYC0S5q0yr0omBfmEnkbgpyN4m9QZE07ILky0RHayA7/HuyAPi9D8u36G6yWbi18QxJpH2Y4KRNlFrNKg+JYMbvTTtjpy6W8NoWq8XK38UBi+oc2Vg9p1rRTndqrUALCyWunuNpsBoMebcNajV8EbTftsSqjcoV+KE/jc1zHa5RlcFs07pI3khrOnCyoAoxSgCv53wZeboXRlo/yeB1kML97us+AkcAAf+RRNwQvUbV+BGejwIOwplG41+GqvjfpcLb8achieDdbSzzVTKX0gPWqBkKgiNzHV7c84oWARFOJPqm1TosnEAQ13VKa4n5RWeL4tk1rT3t5S4Cl0ZlN/nasGHKbt5s9iTyT4xrxtbSp2aMKWtyZNUZF0wpfzZoVl5I7OGmiHT2Z/pRb158HG+dqB4SvSqJrFAG/+6d8xJdm982vRfl+p0CtVIV3Qk=
