version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: install+mutate
          command: bundle install && bundle exec mutant --include lib --require protobuf_nested_struct --use rspec ProtobufNestedStruct*
          environment:
            ARCHFLAGS: "-arch x86_64"