# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_nested_struct/struct.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/type/date_pb'


descriptor_data = "\n#protobuf_nested_struct/struct.proto\x12\x16protobuf_nested_struct\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16google/type/date.proto\"\xaa\x01\n\x12HashMapStringValue\x12\x46\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x36.protobuf_nested_struct.HashMapStringValue.FieldsEntry\x1aL\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.protobuf_nested_struct.Value:\x02\x38\x01\"\x84\x03\n\x05Value\x12\x37\n\nnull_value\x18\x01 \x01(\x0e\x32!.protobuf_nested_struct.NullValueH\x00\x12\x16\n\x0c\x64ouble_value\x18\x02 \x01(\x01H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x05 \x01(\x08H\x00\x12\'\n\ndate_value\x18\x06 \x01(\x0b\x32\x11.google.type.DateH\x00\x12\x35\n\x0ftimestamp_value\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x12\x46\n\x10string_map_value\x18\x14 \x01(\x0b\x32*.protobuf_nested_struct.HashMapStringValueH\x00\x12\x37\n\nlist_value\x18\x15 \x01(\x0b\x32!.protobuf_nested_struct.ListValueH\x00\x42\x06\n\x04kind\":\n\tListValue\x12-\n\x06values\x18\x01 \x03(\x0b\x32\x1d.protobuf_nested_struct.Value*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ProtobufNestedStruct
  HashMapStringValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf_nested_struct.HashMapStringValue").msgclass
  Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf_nested_struct.Value").msgclass
  ListValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf_nested_struct.ListValue").msgclass
  NullValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf_nested_struct.NullValue").enummodule
end
