# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: struct.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/type/date_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ruby_event_store.protobuf.Struct" do
    map :fields, :string, :message, 1, "ruby_event_store.protobuf.Value"
  end
  add_message "ruby_event_store.protobuf.Value" do
    oneof :kind do
      optional :null_value, :enum, 1, "ruby_event_store.protobuf.NullValue"
      optional :double_value, :double, 2
      optional :int_value, :int64, 3
      optional :string_value, :string, 4
      optional :bool_value, :bool, 5
      optional :date_value, :message, 6, "google.type.Date"
      optional :timestamp_value, :message, 7, "google.protobuf.Timestamp"
      optional :struct_value, :message, 20, "ruby_event_store.protobuf.Struct"
      optional :list_value, :message, 21, "ruby_event_store.protobuf.ListValue"
    end
  end
  add_message "ruby_event_store.protobuf.ListValue" do
    repeated :values, :message, 1, "ruby_event_store.protobuf.Value"
  end
  add_enum "ruby_event_store.protobuf.NullValue" do
    value :NULL_VALUE, 0
  end
end

module RubyEventStore
  module Protobuf
    Struct = Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_event_store.protobuf.Struct").msgclass
    Value = Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_event_store.protobuf.Value").msgclass
    ListValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_event_store.protobuf.ListValue").msgclass
    NullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("ruby_event_store.protobuf.NullValue").enummodule
  end
end
