name: protobu_nested_struct_test
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - script
  push:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        ruby: [ruby-3.4, ruby-3.3, ruby-3.2]
        gemfile: [Gemfile, Gemfile.google_protobuf_3_25]
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      RUBYOPT: "--enable-frozen-string-literal"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - run: test -e "${{ matrix.gemfile }}.lock"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
      - run: bin/rspec
